### ISSUE TITLE
error cargar

### ISSUE THREAD

**Issue by mrslide555** [G4lile0/Bobwi#6]
hola, quiero probar a montar un zowi, pero me dice que el archivo es muy grande... ¿que hago mal? ¿me podéis ayudar? Gracias

Tamaño binario del Sketch: 32.584 bytes (de un máximo de 30.720 bytes)
processing.app.debug.RunnerException: Sketch demasiado grande; ver http://www.arduino.cc/en/Guide/Troubleshooting#size para consejos de como reducirlo.
	at processing.app.Sketch.size(Sketch.java:1653)
	at processing.app.Sketch.build(Sketch.java:1586)
	at processing.app.Sketch.build(Sketch.java:1562)
	at processing.app.Editor$DefaultRunHandler.run(Editor.java:1899)
	at java.lang.Thread.run(Thread.java:619)

**Comment by hulkco** [comment]
Que Tarjeta, y IDE Arduino usas y que Programa quieres subir?

**Comment by mrslide555** [comment]
Gracias hulkco, Ya está solucionado, el problema era la versión del arduino, ha bastado con actualizar y volver a compilar. 

¿Esta versión lleva microfono?? He visto otro que ha montado su zowi y le ha añadido micrófono..  Supongo que será para el modo 4..

**Comment by hulkco** [comment]
Todavia no intento lo del microfono, llegue hasta buzzer

**Comment by mrslide555** [comment]
Socorro !! tengo otro problema, meto el codigo en el arduino nano y no hay manera hace pausas, va a trompicones ¿puede ser que me hayan vendido unos arduino lentos? en principio los compre como nano 328. ¿se te ocurre cual es el problema??

gracias

**Comment by mrslide555** [comment]
Ya esta Solucionado, era todo cosa de las baterías, necesita mucha corriente!! Gracias

**Comment by hulkco** [comment]
jejeje, a mi tambien me trajo loco ese problema, yo uso una de 9v Recargable, es mas comodo, saludos, tenemos un grupo en Telegram, #RetoBaileZowi aun estas a tiempo de ingresar y compartir Saludos y Feliz Año.!

**Comment by lobras77** [comment]
Hola. Saqué las piezas con la impresora e iba a conectarlo todo cuando me ha sorprendido que no me compila y no entiendo el porqué. Guardé las librerías en la carpeta y usé el codigo del zowi_base_v2  . Me puede ayudar alguien?
